services:
  postgres:
    image: postgres:17
    container_name: pesatrack-postgres
    restart: always
    environment:
      POSTGRES_USER: pesatrack
      POSTGRES_PASSWORD: pesatrack_password
      POSTGRES_DB: pesatrack_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
